#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-redis
Version  : 4.1.4
Release  : 1
URL      : https://files.pythonhosted.org/packages/6e/ac/f2b72c20e106b610f943da052ea179e8c90453a1341ce5beabd75a59eeda/redis-4.1.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/6e/ac/f2b72c20e106b610f943da052ea179e8c90453a1341ce5beabd75a59eeda/redis-4.1.4.tar.gz
Summary  : Python client for Redis database and key-value store
Group    : Development/Tools
License  : MIT
Requires: pypi-redis-license = %{version}-%{release}
Requires: pypi-redis-python = %{version}-%{release}
Requires: pypi-redis-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(deprecated)
BuildRequires : pypi(packaging)

%description
# redis-py
The Python interface to the Redis key-value store.
[![CI](https://github.com/redis/redis-py/workflows/CI/badge.svg?branch=master)](https://github.com/redis/redis-py/actions?query=workflow%3ACI+branch%3Amaster)
[![docs](https://readthedocs.org/projects/redis/badge/?version=stable&style=flat)](https://redis-py.readthedocs.io/en/stable/)
[![MIT licensed](https://img.shields.io/badge/license-MIT-blue.svg)](./LICENSE)
[![pypi](https://badge.fury.io/py/redis.svg)](https://pypi.org/project/redis/)
[![codecov](https://codecov.io/gh/redis/redis-py/branch/master/graph/badge.svg?token=yenl5fzxxr)](https://codecov.io/gh/redis/redis-py)
[![Total alerts](https://img.shields.io/lgtm/alerts/g/redis/redis-py.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/redis/redis-py/alerts/)

%package license
Summary: license components for the pypi-redis package.
Group: Default

%description license
license components for the pypi-redis package.


%package python
Summary: python components for the pypi-redis package.
Group: Default
Requires: pypi-redis-python3 = %{version}-%{release}

%description python
python components for the pypi-redis package.


%package python3
Summary: python3 components for the pypi-redis package.
Group: Default
Requires: python3-core
Provides: pypi(redis)
Requires: pypi(deprecated)
Requires: pypi(packaging)

%description python3
python3 components for the pypi-redis package.


%prep
%setup -q -n redis-4.1.4
cd %{_builddir}/redis-4.1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1646323063
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-redis
cp %{_builddir}/redis-4.1.4/LICENSE %{buildroot}/usr/share/package-licenses/pypi-redis/a4b61fde3ceaed3091f9f7ac886713a60beef947
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-redis/a4b61fde3ceaed3091f9f7ac886713a60beef947

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
